FROM node:20-alpine

RUN apk add --no-cache git

WORKDIR /app
RUN git clone https://github.com/rmyndharis/OpenWA.git .
RUN npm install

RUN cp .env.minimal .env
RUN mkdir -p data/sessions data/media

EXPOSE 2785 2886

CMD ["npm", "run", "start:prod"]
